INSERT INTO EDUCATION (UNIVERSITY) VALUES ("BANGKOK");
INSERT INTO EDUCATION (UNIVERSITY) VALUES ("RANGSIT");

INSERT INTO EMPLOYEE (NAME, EDUCATION_ID) VALUES ('Employee1', 1);
INSERT INTO EMPLOYEE (NAME, EDUCATION_ID) VALUES ('Employee2', 2);
