INSERT INTO EDUCATION (UNIVERSITY, GPA, FACULTY, MAJOR, DEGREE) VALUES ("BANGKOK", "3.00", "SCIENCE", "COMPUTER SCIENCE", "DEGRREE");
INSERT INTO EDUCATION (UNIVERSITY, GPA, FACULTY, MAJOR, DEGREE) VALUES ("RANGSIT", "3.00", "SCIENCE", "COMPUTER SCIENCE", "DEGRREE");
INSERT INTO EDUCATION (UNIVERSITY, GPA, FACULTY, MAJOR, DEGREE) VALUES ("RANGSIT3", "3.00", "SCIENCE", "COMPUTER SCIENCE", "DEGRREE");

--INSERT INTO EMPLOYEE (NAME, EDUCATION_ID) VALUES ('Employee1', 1);
--INSERT INTO EMPLOYEE (NAME, EDUCATION_ID) VALUES ('Employee2', 2);
